### ISSUE TITLE
Create Service Layer Skeleton

### ISSUE THREAD

**Issue by Matt-Hays** [tkm3d1a/cs5324_s24_class_project#10]
### Create the Services Layer skeleton. 

- Blank service classes with appropriate annotations and dependencies **only**.

*This task is intended to allow others to work collaboratively on use case tasks without conflict.*

**Comment by tkm3d1a** [comment]
@Matt-Hays Service layer skeleton should be in place - give it a review and we can close it out and merge to update the controller branch as well
