### ISSUE TITLE
Implement Use Case #1 - View Media Library

### ISSUE THREAD

**Issue by Matt-Hays** [tkm3d1a/cs5324_s24_class_project#13]
**UC: UC01 – View media library** 

**Scope:** CS Automated Information Timeline 

**Level:** User goal 

**Primary Actor:** Audience 

**Stakeholders and Interests:** 

Audience wants the ability to view all shared media through the media library 

Faculty wants to be able to allow guests to view media shared by them 

Office Manager wants to ensure that all media is available to be seen through the web portal 

Admin wants to be sure that approved media can be displayed to the audience 
  
**Preconditions:** 

Media library contains approved media items 

**Postconditions:** 

Media library is shared with the audience 

**Main Success Scenario:** 

- Audience member scans available QR code 

- System provides appropriate URL for main home page 

- Audience member navigates to URL 

- Audience member selects “Media library” option 

- System presents full media library view 

**Alternative Flows:**  

- 3A: URL is down 

-- Audience member alerts faculty or office manager 

-- Office manager or faculty review system status 

- 5A: Multiple pages available 

-- System presents paged view with limit of items 

-- Audience member selects ‘next page’ 

-- System returns next set of results 

-- Continue until end of media library is returned 

**System Operations** 

- scanQRCode() 

- selectMediaLibrary() 

**Operation contracts**  

**Operation:** selectMediaLibrary() 

**Pre-conditions:**  

- Media items, m, exists in system 

- m is approved for view 

**Post-conditions:**  

- List of media, ml, is created 

- ml is returned to user

**Comment by tkm3d1a** [comment]
Going to include all basic Media crud operations on this Issue in support of managing media use case

**Comment by Matt-Hays** [comment]
Please do as you see fit. I just wanted to get all tasks on the board and get the ball rolling.
